### ISSUE TITLE
Readme improved

### ISSUE THREAD

**Issue by ignatandrei** [hermanussen/MockSourceGenerator#1]
Could you please improve the readme ? 
I do not understand how I use in a test scenario

**Comment by hermanussen** [comment]
I guess the readme could use a bit of love.

Please note that some of the comments in the code examples clarify the way it can be used. Maybe that is not clear.

Perhaps the info here can also help. I can work that into the readme. -> https://twitter.com/knifecore/status/1329092901263998978?s=19

Could you give me some pointers on what  is not clear to you from the readme?

**Comment by hermanussen** [comment]
I guess what might not seem intuitive at first is how mock classes are generated on the fly as you type "new WhateverMock()". Maybe I should make that clear.

I think that makes it really easy to use, but it can seem a bit weird at first.

**Comment by ignatandrei** [comment]
I think that you should show the 
IExternalSystemService
definition. And be more clear that, once this line is written,
(IExternalSystemService) new MyMock

the code will be generated right away. 
And , on a separate topic, I think that you generate a Stub, not a Mock : https://blog.pragmatists.com/test-doubles-fakes-mocks-and-stubs-1a7491dfa3da

**Comment by hermanussen** [comment]
I agree. I'll clarify that in the readme.

Actually, there is functionality to verify (which distinguishes mocks from stubs), so I think Mock is appropriate. You can see an example of that in the readme as well (`HistoryEntries` property). But that could be clarified better as well.

I'm not too happy with how that works though; I think it should be easier to verify. I'm open to suggestions on how to do this.

**Comment by hermanussen** [comment]
@ignatandrei I updated the readme based on your feedback. Please let me know if you understand it better now.

Any other feedback is appreciated as well. I hope you like it.

By the way, the [unit tests in this project](https://github.com/hermanussen/MockSourceGenerator/tree/main/MocksSourceGeneratorTests) are a good source for seeing what types of scenarios I thought of.

**Comment by ignatandrei** [comment]
Yes, thank you!
